# page config
theme: jekyll-theme-minimal
title: rageworx github IO page
name : rageworx's GIO
description: rageworx's github IO
search: true
search_full_content: true
# author config
author:
  name : Raph.K.
  avatar: "/assets/images/bio-photo.jpg"
  bio: "rageworx"
  github: "rageworx"

# other configs
show_downloads: true
github:
  fltk-custom: https://github.com/rageworx/fltk-custom
  fltk-imgtk: https://github.com/rageworx/fl_imgtk
  FLFTRender: https://github.com/rageworx/FLFTRender
  FLTermEx: https://github.com/rageworx/FLTermEx
  libendetool: https://github.com/rageworx/libendetool
  Huawei_tool: https://github.com/rageworx/Huawei_Tool
  gitrepo: https://github.com/rageworx
  description: Raph.K's github IO page.
