###########
# site.title, site.url, site.author.name
theme: jekyll-theme-minimal
title:   'RAGEWORX github IO page'
author:
  name:  'Raph.K'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false
